[project]
name = "retail-mind"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { email = "vanamgowtham123gmail.com" }
]
requires-python = ">=3.11.0"
dependencies = [
    "sentence-transformers>=6.1.0",
    "uvicorn>=0.54.0",
]

[project.scripts]
retail-mind = "retail_mind:main"

[build-system]
requires = ["uv_build>=0.12.19,<0.13.0"]
build-backend = "uv_build"
